suggestion:
    resource: "@SuggestionBundle/Controller/"
    type:     annotation
    prefix:   /suggestion/

survey:
    resource: "@SurveyBundle/Controller/"
    type:     annotation
    prefix:   /survey/